-- Migration: 001_create_inventory_alerts
-- Module:     M2 Purchasing & Inventory Agent
-- Sprint:     0 (Architecture & Planning)
-- Depends on: products table (public schema, uuid PK)
--
-- Purpose:
--   Stores every alert generated by InventoryCheckNode.
--   One row = one problem detected for one product at one point in time.
--   The Dashboard reads this table to render the AlertsPanel.
--
-- alert_type values map 1-to-1 to M2State.DetectionType:
--   low_stock          → quantity <= reorder_point
--   predicted_shortage → days_until_stockout < lead_time_days
--   slow_moving        → turnover_rate < threshold (Phase 1)
--   near_expiry        → expiry_date within N days (Phase 1)
--
-- Run idempotently (safe to re-run):
--   psql $DATABASE_URL -f 001_create_inventory_alerts.sql

-- ── 1. Create alert_type enum (idempotent) ───────────────────────
DO $$
BEGIN
    CREATE TYPE alert_type_enum AS ENUM (
        'low_stock',
        'predicted_shortage',
        'slow_moving',
        'near_expiry'
    );
EXCEPTION WHEN duplicate_object THEN
    NULL; -- already exists, skip
END
$$;

-- ── 2. Create inventory_alerts table ─────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_alerts (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The product this alert is about.
    -- product_id is uuid (matches products.id — NOT integer).
    product_id  UUID        NOT NULL REFERENCES products(id) ON DELETE CASCADE,

    -- What kind of problem was detected.
    alert_type  alert_type_enum NOT NULL,

    -- Human-readable summary (in the user's language, set by AlertGeneratorNode).
    -- Example AR: "رصيد لابتوب Dell XPS 13 وصل للحد الأدنى — مطلوب إعادة طلب 20 وحدة"
    -- Example EN: "Dell XPS 13 stock hit reorder point — 20 units needed"
    message     TEXT,

    -- Structured data used by the Dashboard and LLM nodes.
    -- Schema is loose (JSONB) to avoid a migration for each new metric.
    -- Phase 0 keys:
    --   current_quantity:    int
    --   reorder_point:       int
    --   suggested_quantity:  int
    --   lead_time_days:      int
    -- Phase 1 additional keys:
    --   days_until_stockout: float
    --   turnover_rate:       float
    --   avg_daily_sales:     float
    --   expiry_date:         str (ISO date)
    --   days_to_expiry:      int
    metadata    JSONB       NOT NULL DEFAULT '{}',

    -- Lifecycle: open → acknowledged (user saw it) → resolved (restocked/sold/expired)
    status      VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'acknowledged', 'resolved')),

    -- The RFQ created in response to this alert (set after Sprint 2).
    -- NULL until an RFQ is generated.
    rfq_id      UUID        REFERENCES rfqs(id) ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── 3. Indexes ────────────────────────────────────────────────────
-- Scan by product (AlertsPanel: "show all alerts for this product")
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_product
    ON inventory_alerts(product_id);

-- Scan by type (Dashboard filter: "show only low_stock alerts")
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_type
    ON inventory_alerts(alert_type);

-- Scan by status (default view: show open alerts only)
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_status
    ON inventory_alerts(status)
    WHERE status = 'open';

-- Sort by most recent first (Dashboard default ordering)
CREATE INDEX IF NOT EXISTS idx_inventory_alerts_created_desc
    ON inventory_alerts(created_at DESC);

-- ── 4. Auto-update updated_at on row change ───────────────────────
-- Reuses the same trigger function pattern as other tables in the project.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_inventory_alerts_updated_at ON inventory_alerts;
CREATE TRIGGER trg_inventory_alerts_updated_at
    BEFORE UPDATE ON inventory_alerts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
