-- Migration: 002_create_rfqs
-- Module:     M2 Purchasing & Inventory Agent
-- Sprint:     0 (Architecture & Planning)
-- Depends on: products, vendors, inventory_alerts (001)
--
-- Purpose:
--   Stores Request-For-Quotation drafts generated by RFQBuilderNode.
--   Each RFQ is tied to one product and optionally linked to the
--   inventory alert that triggered it.
--
--   The thread_id column is critical for Phase 2 (Async Procurement Loop):
--   after the RFQ is sent to the supplier, the LangGraph is paused
--   (AsyncPostgresSaver checkpoint). When supplier offers arrive
--   (POST /api/v1/m2/offers), the server looks up thread_id here
--   and resumes the same graph instance.
--
-- Status lifecycle:
--   draft → approved → sent → analyzing → closed
--
-- Run idempotently:
--   psql $DATABASE_URL -f 002_create_rfqs.sql

-- ── 1. Create rfq_status enum (idempotent) ────────────────────────
DO $$
BEGIN
    CREATE TYPE rfq_status_enum AS ENUM (
        'draft',      -- RFQBuilderNode generated the text, not yet reviewed
        'approved',   -- Manager clicked "Approve & Send" on the Dashboard
        'sent',       -- n8n Email Node delivered it to the supplier(s)
        'analyzing',  -- Offers received; OfferAnalysisNode is running
        'closed'      -- Final decision made (accepted an offer or cancelled)
    );
EXCEPTION WHEN duplicate_object THEN
    NULL;
END
$$;

-- ── 2. Create rfqs table ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rfqs (
    id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The product we are requesting a quotation for.
    product_id  UUID            NOT NULL REFERENCES products(id) ON DELETE RESTRICT,

    -- Array of vendor UUIDs to send this RFQ to.
    -- NULL until HumanApprovalNode confirms and selects vendors.
    -- Stored as UUID[] matching vendors.id (uuid PK).
    vendor_ids  UUID[],

    -- How many units to order (computed by InventoryCheckNode).
    quantity    INTEGER         NOT NULL CHECK (quantity > 0),

    -- Unit of measure (e.g. "unit", "box", "kg") — defaults to "unit".
    unit        VARCHAR(30)     NOT NULL DEFAULT 'unit',

    -- The full email draft text generated by RFQBuilderNode.
    -- Language (AR or EN) set per user_context.language.
    draft_text  TEXT,

    -- Current lifecycle stage.
    status      rfq_status_enum NOT NULL DEFAULT 'draft',

    -- LangGraph AsyncPostgresSaver checkpoint key.
    -- Format: "m2-rfq-{id}"
    -- Set when status transitions to 'sent'.
    -- Used to resume the graph when offers arrive.
    thread_id   VARCHAR(128)    UNIQUE,

    -- The inventory_alerts row that triggered this RFQ.
    -- NULL for manually-created RFQs (future feature).
    alert_id    UUID            REFERENCES inventory_alerts(id) ON DELETE SET NULL,

    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- ── 3. Indexes ────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_rfqs_product
    ON rfqs(product_id);

-- Status filter (Dashboard: "show pending approvals")
CREATE INDEX IF NOT EXISTS idx_rfqs_status
    ON rfqs(status);

-- Fast lookup by thread_id when offers arrive and need to resume the graph
CREATE INDEX IF NOT EXISTS idx_rfqs_thread_id
    ON rfqs(thread_id)
    WHERE thread_id IS NOT NULL;

-- ── 4. Add the FK from inventory_alerts → rfqs (now that rfqs exists) ───────
ALTER TABLE inventory_alerts
    ADD CONSTRAINT IF NOT EXISTS fk_inventory_alerts_rfq
    FOREIGN KEY (rfq_id) REFERENCES rfqs(id) ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED;

-- ── 5. Auto-update updated_at ─────────────────────────────────────
DROP TRIGGER IF EXISTS trg_rfqs_updated_at ON rfqs;
CREATE TRIGGER trg_rfqs_updated_at
    BEFORE UPDATE ON rfqs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
