from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List, Any
from pydantic import BaseModel

from backend.core.database import get_db_session_dep
from backend.models.m2_pricing_recommendation import PricingRecommendation

router = APIRouter(prefix="/m2/pricing", tags=["M2 Pricing"])

class PricingRecResponse(BaseModel):
    id: str
    product_id: str
    recommendation: str
    created_at: str

@router.get("", response_model=List[PricingRecResponse])
async def get_pricing_recommendations(session: AsyncSession = Depends(get_db_session_dep)) -> Any:
    """
    Returns the latest pricing recommendations generated by the Pricing Advisor Node.
    """
    stmt = select(PricingRecommendation).order_by(PricingRecommendation.created_at.desc()).limit(50)
    result = await session.execute(stmt)
    recs = result.scalars().all()
    
    return [
        PricingRecResponse(
            id=str(r.id),
            product_id=str(r.product_id),
            recommendation=r.recommendation_text,
            created_at=r.created_at.isoformat()
        ) for r in recs
    ]
