"""Structured contracts shared by routing, query execution, and evaluation."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class DateRange(BaseModel):
    start: str | None = None
    end: str | None = None


class VisualizationHints(BaseModel):
    chart_type: Literal[
        "line_chart",
        "bar_chart",
        "table",
        "metric_card",
        "formatted_text_list",
        "alert",
        "narrative",
        "direct_text",
    ] | None = None
    x_axis: str | None = None
    y_axis: str | None = None
    group_by: str | None = None
    sort_by: str | None = None


class AnalysisEntity(BaseModel):
    type: str
    value: str


class AnalysisFrame(BaseModel):
    metric: str | None = None
    entities: list[AnalysisEntity] = Field(default_factory=list)
    dimensions: list[str] | None = Field(default_factory=list)
    filters: dict[str, Any] | None = Field(default_factory=dict)
    date_range: DateRange | None = None
    comparison_range: DateRange | None = None
    grain: str | None = None
    analysis_type: str | None = None
    requested_output: str | None = None


class RouteDecision(BaseModel):
    assigned_tier: Literal["T0", "T1", "T2", "T3", "T4", "T5", "T6"]
    domain_intent: str
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    signals: list[str] = Field(default_factory=list)
    analysis_frame: AnalysisFrame = Field(default_factory=AnalysisFrame)
    missing_slots: list[str] = Field(default_factory=list)


class GeneratedQuery(BaseModel):
    sql: str
    purpose: str
    expected_columns: list[str] = Field(default_factory=list)
    expected_grain: str = "unknown"
    referenced_tables: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class QueryValidation(BaseModel):
    is_valid: bool
    error_category: str | None = None
    message: str | None = None
    tables: list[str] = Field(default_factory=list)
    columns: list[str] = Field(default_factory=list)
    sql_fingerprint: str = ""
    normalized_sql: str | None = None


class QueryArtifact(BaseModel):
    source: Literal["template", "nl2sql"]
    purpose: str
    sql_fingerprint: str
    parameters: dict[str, Any] = Field(default_factory=dict)
    referenced_tables: list[str] = Field(default_factory=list)
    referenced_columns: list[str] = Field(default_factory=list)
    validation: dict[str, Any] = Field(default_factory=dict)
    execution_status: str
    row_count: int = 0
    duration_ms: float = 0.0
    result_sample: list[dict[str, Any]] = Field(default_factory=list)
    error_category: str | None = None
    error_message: str | None = None


class ResultEvaluation(BaseModel):
    status: Literal[
        "complete", "partial", "empty", "suspicious", "invalid", "failed"
    ]
    coverage: float = Field(ge=0.0, le=1.0)
    evidence: list[str] = Field(default_factory=list)
    gaps: list[str] = Field(default_factory=list)
    needs_requery: bool = False
    format_hint: str = "narrative"


class PlanStep(BaseModel):
    id: str
    purpose: str
    preferred_tool: Literal["template", "nl2sql", "python"]
    expected_columns: list[str] = Field(default_factory=list)
    expected_grain: str = "unknown"
    depends_on: list[str] = Field(default_factory=list)
    legend_label: str | None = Field(
        None,
        description="Short user-facing label for this step's data series in chart legends/table columns, e.g. 'أوامر البيع' or 'الفواتير'"
    )
    visualization_hints: VisualizationHints | None = Field(
        default=None,
        description="Optional output generated by planner. Advisory hints for how the data should be displayed."
    )


class AnalyticalPlan(BaseModel):
    steps: list[PlanStep] = Field(default_factory=list)
    final_synthesis: str = ""


class FrameUpdate(BaseModel):
    """A single atomic change to apply on the prior analysis frame."""
    field: Literal[
        "metric", "date_range", "comparison_range", "grain",
        "analysis_type", "requested_output",
    ]
    value: Any


class FollowUpResolution(BaseModel):
    """LLM output: understand what the user wants to change in the analysis."""
    mode: Literal[
        "reason_only", "refine", "drill_down", "compare",
        "requery", "summarize",
    ]
    reasoning: str = ""
    add_filters: dict[str, str] = Field(
        default_factory=dict,
        description="New filters to add, e.g. {'customer': 'أحمد'}",
    )
    remove_filters: list[str] = Field(
        default_factory=list,
        description="Filter keys to remove from the prior frame",
    )
    add_dimensions: list[str] = Field(
        default_factory=list,
        description="New dimensions to add, e.g. ['product', 'region']",
    )
    remove_dimensions: list[str] = Field(
        default_factory=list,
        description="Dimensions to remove from the prior frame",
    )
    add_entities: list[AnalysisEntity] = Field(
        default_factory=list,
        description="New entities to scope the analysis",
    )
    frame_updates: list[FrameUpdate] = Field(
        default_factory=list,
        description="Direct field overrides on the analysis frame",
    )
    new_query_text: str | None = Field(
        default=None,
        description="Rewritten standalone query if the original is too short",
    )

